server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://vuabycorbqwrtl:a85345feda1737ec6f1afa974d8fbdb76f2bb3907edb30feb5fc2bac889d4f57@ec2-34-200-94-86.compute-1.amazonaws.com:5432/d7v2ficgtakv4d
    username: vuabycorbqwrtl
    password: a85345feda1737ec6f1afa974d8fbdb76f2bb3907edb30feb5fc2bac889d4f57
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Dev Week Santander - DIO